apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: trend-service
=======
  name: trend-app-service
>>>>>>> 2736d7d (Initial commit of Trend_app)
spec:
  type: LoadBalancer
  selector:
    app: trend-app
  ports:
<<<<<<< HEAD
    - protocol: TCP
      port: 80
      targetPort: 3000
=======
    - port: 80
      targetPort: 80
      protocol: TCP
>>>>>>> 2736d7d (Initial commit of Trend_app)
